name: Android build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup git config (for patch command)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: lib
          path: srtdroid-*/build/outputs/aar
      - name: Upload APKs
        uses: actions/upload-artifact@v7
        with:
          name: apks
          path: |
            example/build/outputs/apk/debug/example-debug.apk
